name: "Run"
on:
  push:
    branches:
      - "main"

jobs:
  defaults:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ github.actor == 'dependabot[bot]' && fromJson('["ubuntu-latest"]') || fromJson('["ubuntu-latest", "windows-latest", "macOS-latest"]') }}
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - uses: ./

    - name: Verify
      run: emcc -v
  actions-use-cache-test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Setup emsdk (use cache if found, create otherwise)
        uses: ./
        with:
          version: 4.0.9
          actions-cache-folder: 'emsdk-cache-folder'
          no-cache: true

      - name: Verify
        run: emcc -v
  no-install:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: ./
        with:
          no-install: true

      - name: Verify
        run: emsdk list
  tot:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Setup emsdk (use cache if found, create otherwise)
        uses: ./
        with:
          version: tot
          no-cache: true
          update-tags: true

      - name: Verify
        run: emcc -v
